version: '3.8'

services: 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nodeapp: 
    build: .
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  postgres-data: